global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"

ping: {}

providers:
  docker:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"

log:
  level: INFO
EOF