global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    # Redirect all HTTP to HTTPS
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt

ping: {}

providers:
  docker:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"

certificatesResolvers:
  letsencrypt:
    acme:
      email: your-email@example.com # CHANGE THIS!
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web
      # Uncomment for testing (to avoid rate limits)
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory

log:
  level: INFO
